"""sales + production + aux-line transformation

Revision ID: 05b98cf23661
Revises: bc154533a423
Create Date: 2026-07-06 14:16:56.733971
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05b98cf23661'
down_revision: Union[str, None] = 'bc154533a423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_person', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_name'), 'customer', ['name'], unique=True)
    op.create_table('transformation_run',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_number', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('line_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('operator_1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('operator_2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('machine', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'PLANNED', 'OPEN', 'IN_PROGRESS', 'PARTIAL', 'RELEASED', 'COMPLETED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transformation_run_line_code'), 'transformation_run', ['line_code'], unique=False)
    op.create_index(op.f('ix_transformation_run_run_number'), 'transformation_run', ['run_number'], unique=True)
    op.create_table('sales_order',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'PLANNED', 'OPEN', 'IN_PROGRESS', 'PARTIAL', 'RELEASED', 'COMPLETED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_order_customer_id'), 'sales_order', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_order_order_number'), 'sales_order', ['order_number'], unique=True)
    op.create_table('transformation_step',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_qty', sa.Float(), nullable=True),
    sa.Column('input_uom', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('output_qty', sa.Float(), nullable=True),
    sa.Column('output_uom', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('loss_qty', sa.Float(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['transformation_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transformation_step_run_id'), 'transformation_step', ['run_id'], unique=False)
    op.create_table('sales_order_line',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('production_line', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_order_line_sales_order_id'), 'sales_order_line', ['sales_order_id'], unique=False)
    op.create_table('shipment',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_number', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'PLANNED', 'OPEN', 'IN_PROGRESS', 'PARTIAL', 'RELEASED', 'COMPLETED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_sales_order_id'), 'shipment', ['sales_order_id'], unique=False)
    op.create_index(op.f('ix_shipment_shipment_number'), 'shipment', ['shipment_number'], unique=True)
    op.create_table('production_order',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prod_order_number', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('sales_order_line_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('line_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'PLANNED', 'OPEN', 'IN_PROGRESS', 'PARTIAL', 'RELEASED', 'COMPLETED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['sales_order_line_id'], ['sales_order_line.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_order_line_code'), 'production_order', ['line_code'], unique=False)
    op.create_index(op.f('ix_production_order_prod_order_number'), 'production_order', ['prod_order_number'], unique=True)
    op.create_index(op.f('ix_production_order_product_id'), 'production_order', ['product_id'], unique=False)
    op.create_table('transformation_output',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('grade', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('output_lot_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('uom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('yield_pct', sa.Float(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['output_lot_id'], ['raw_material_lot.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['transformation_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transformation_output_run_id'), 'transformation_output', ['run_id'], unique=False)
    op.create_table('production_batch',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('production_order_id', sa.Integer(), nullable=False),
    sa.Column('parent_batch_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('line_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_station', sa.Enum('FC', 'LAMINATING', 'COLD_PRESS', 'HOT_PRESS', 'BLEACH', 'REPAIR', 'SANDING', 'GRADING', 'PACKING', 'FG_RECEIVING', 'FG_WAREHOUSE', name='stationcode'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ON_HOLD', 'SPLIT', 'NCG', 'COMPLETED', 'SCRAPPED', name='batchstatus'), nullable=False),
    sa.Column('split_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['parent_batch_id'], ['production_batch.id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_batch_batch_number'), 'production_batch', ['batch_number'], unique=True)
    op.create_index(op.f('ix_production_batch_current_station'), 'production_batch', ['current_station'], unique=False)
    op.create_index(op.f('ix_production_batch_line_code'), 'production_batch', ['line_code'], unique=False)
    op.create_index(op.f('ix_production_batch_production_order_id'), 'production_batch', ['production_order_id'], unique=False)
    op.create_index(op.f('ix_production_batch_status'), 'production_batch', ['status'], unique=False)
    op.create_table('station_record',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('station', sa.Enum('FC', 'LAMINATING', 'COLD_PRESS', 'HOT_PRESS', 'BLEACH', 'REPAIR', 'SANDING', 'GRADING', 'PACKING', 'FG_RECEIVING', 'FG_WAREHOUSE', name='stationcode'), nullable=False),
    sa.Column('pcs_in', sa.Integer(), nullable=False),
    sa.Column('pcs_out', sa.Integer(), nullable=False),
    sa.Column('operator_1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('operator_2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('machine', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('time_min', sa.Integer(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['production_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_record_batch_id'), 'station_record', ['batch_id'], unique=False)
    op.create_index(op.f('ix_station_record_station'), 'station_record', ['station'], unique=False)
    op.create_table('transformation_input',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('uom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['production_batch.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['raw_material_lot.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['transformation_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transformation_input_run_id'), 'transformation_input', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transformation_input_run_id'), table_name='transformation_input')
    op.drop_table('transformation_input')
    op.drop_index(op.f('ix_station_record_station'), table_name='station_record')
    op.drop_index(op.f('ix_station_record_batch_id'), table_name='station_record')
    op.drop_table('station_record')
    op.drop_index(op.f('ix_production_batch_status'), table_name='production_batch')
    op.drop_index(op.f('ix_production_batch_production_order_id'), table_name='production_batch')
    op.drop_index(op.f('ix_production_batch_line_code'), table_name='production_batch')
    op.drop_index(op.f('ix_production_batch_current_station'), table_name='production_batch')
    op.drop_index(op.f('ix_production_batch_batch_number'), table_name='production_batch')
    op.drop_table('production_batch')
    op.drop_index(op.f('ix_transformation_output_run_id'), table_name='transformation_output')
    op.drop_table('transformation_output')
    op.drop_index(op.f('ix_production_order_product_id'), table_name='production_order')
    op.drop_index(op.f('ix_production_order_prod_order_number'), table_name='production_order')
    op.drop_index(op.f('ix_production_order_line_code'), table_name='production_order')
    op.drop_table('production_order')
    op.drop_index(op.f('ix_shipment_shipment_number'), table_name='shipment')
    op.drop_index(op.f('ix_shipment_sales_order_id'), table_name='shipment')
    op.drop_table('shipment')
    op.drop_index(op.f('ix_sales_order_line_sales_order_id'), table_name='sales_order_line')
    op.drop_table('sales_order_line')
    op.drop_index(op.f('ix_transformation_step_run_id'), table_name='transformation_step')
    op.drop_table('transformation_step')
    op.drop_index(op.f('ix_sales_order_order_number'), table_name='sales_order')
    op.drop_index(op.f('ix_sales_order_customer_id'), table_name='sales_order')
    op.drop_table('sales_order')
    op.drop_index(op.f('ix_transformation_run_run_number'), table_name='transformation_run')
    op.drop_index(op.f('ix_transformation_run_line_code'), table_name='transformation_run')
    op.drop_table('transformation_run')
    op.drop_index(op.f('ix_customer_name'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
