"""fold logs into item: drop log/log_arrival/log_document, add LOG item kind

Revision ID: 1531632666c0
Revises: faafa3e04a81
Create Date: 2026-07-16 15:17:32.575264
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1531632666c0'
down_revision: Union[str, None] = 'faafa3e04a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_document_log_id'), table_name='log_document')
    op.drop_table('log_document')
    op.drop_index(op.f('ix_log_arrival_id'), table_name='log')
    op.drop_index(op.f('ix_log_log_code'), table_name='log')
    op.drop_index(op.f('ix_log_log_number'), table_name='log')
    op.drop_table('log')
    op.drop_index(op.f('ix_log_arrival_arrival_code'), table_name='log_arrival')
    op.drop_table('log_arrival')
    op.sync_enum_values(
        enum_schema='public',
        enum_name='itemkind',
        new_values=['VENEER', 'BOARD', 'LOG', 'GLUE_COMPONENT', 'CONSUMABLE', 'PACKING', 'OTHER'],
        affected_columns=[TableReference(table_schema='public', table_name='item', column_name='kind')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='itemkind',
        new_values=['VENEER', 'BOARD', 'GLUE_COMPONENT', 'CONSUMABLE', 'PACKING', 'OTHER'],
        affected_columns=[TableReference(table_schema='public', table_name='item', column_name='kind')],
        enum_values_to_rename=[],
    )
    op.create_table('log_document',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('log_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doc_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('stored_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['log.id'], name=op.f('log_document_log_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('log_document_pkey'))
    )
    op.create_index(op.f('ix_log_document_log_id'), 'log_document', ['log_id'], unique=False)
    op.create_table('log',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('log_number', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('arrival_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('log_code', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('species_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grade', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('length_in', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('length_m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('diameter_in', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('diameter_m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume_ft3', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume_m3', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['arrival_id'], ['log_arrival.id'], name=op.f('log_arrival_id_fkey')),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], name=op.f('log_species_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('log_pkey'))
    )
    op.create_index(op.f('ix_log_log_number'), 'log', ['log_number'], unique=True)
    op.create_index(op.f('ix_log_log_code'), 'log', ['log_code'], unique=False)
    op.create_index(op.f('ix_log_arrival_id'), 'log', ['arrival_id'], unique=False)
    op.create_table('log_arrival',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('arrival_code', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('arrival_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('container_ref', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('log_arrival_supplier_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('log_arrival_pkey'))
    )
    op.create_index(op.f('ix_log_arrival_arrival_code'), 'log_arrival', ['arrival_code'], unique=True)
    # ### end Alembic commands ###
