"""reshape GlueRecipe to a glue BOM (components kg + applicability)

Revision ID: 27dddf09e70e
Revises: 1531632666c0
Create Date: 2026-07-16 16:18:54.196303
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27dddf09e70e'
down_revision: Union[str, None] = '1531632666c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('glue_recipe', sa.Column('total_kg', sa.Float(), nullable=False, server_default='0'))
    op.add_column('glue_recipe', sa.Column('veneer_thickness', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('glue_recipe', sa.Column('wood_species', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('glue_recipe', sa.Column('core_board', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('glue_recipe', sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    op.drop_column('glue_recipe', 'filler_ratio')
    op.drop_column('glue_recipe', 'water_ratio')
    op.drop_column('glue_recipe', 'hardener_ratio')
    op.drop_column('glue_recipe', 'extender_ratio')
    op.drop_column('glue_recipe', 'material_links')
    op.drop_column('glue_recipe', 'resin_ratio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('glue_recipe', sa.Column('resin_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('glue_recipe', sa.Column('material_links', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('glue_recipe', sa.Column('extender_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('glue_recipe', sa.Column('hardener_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('glue_recipe', sa.Column('water_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('glue_recipe', sa.Column('filler_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('glue_recipe', 'components')
    op.drop_column('glue_recipe', 'core_board')
    op.drop_column('glue_recipe', 'wood_species')
    op.drop_column('glue_recipe', 'veneer_thickness')
    op.drop_column('glue_recipe', 'total_kg')
    # ### end Alembic commands ###
