"""logs + aux-line process model (PVS/PSP recipes+records, PUV finishing job, rework)

Revision ID: 2edddf20dcb4
Revises: debe45413562
Create Date: 2026-07-08 15:28:05.169592
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2edddf20dcb4'
down_revision: Union[str, None] = 'debe45413562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heating_vat',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vat_number', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heating_vat_vat_number'), 'heating_vat', ['vat_number'], unique=True)
    op.create_table('transformation_recipe',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transformation_recipe_code'), 'transformation_recipe', ['code'], unique=True)
    op.create_index(op.f('ix_transformation_recipe_line_code'), 'transformation_recipe', ['line_code'], unique=False)
    op.create_table('log_arrival',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arrival_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('container_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_arrival_arrival_code'), 'log_arrival', ['arrival_code'], unique=True)
    op.create_table('log',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_number', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('arrival_id', sa.Integer(), nullable=False),
    sa.Column('log_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=True),
    sa.Column('grade', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('length_in', sa.Float(), nullable=True),
    sa.Column('length_m', sa.Float(), nullable=True),
    sa.Column('diameter_in', sa.Float(), nullable=True),
    sa.Column('diameter_m', sa.Float(), nullable=True),
    sa.Column('volume_ft3', sa.Float(), nullable=True),
    sa.Column('volume_m3', sa.Float(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['arrival_id'], ['log_arrival.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_arrival_id'), 'log', ['arrival_id'], unique=False)
    op.create_index(op.f('ix_log_log_code'), 'log', ['log_code'], unique=False)
    op.create_index(op.f('ix_log_log_number'), 'log', ['log_number'], unique=True)
    op.create_table('transformation_recipe_line',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('uom', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('grade', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expected_yield_pct', sa.Float(), nullable=True),
    sa.Column('expected_loss_pct', sa.Float(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['transformation_recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transformation_recipe_line_kind'), 'transformation_recipe_line', ['kind'], unique=False)
    op.create_index(op.f('ix_transformation_recipe_line_recipe_id'), 'transformation_recipe_line', ['recipe_id'], unique=False)
    op.create_table('log_document',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stored_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_document_log_id'), 'log_document', ['log_id'], unique=False)
    op.create_table('finishing_job',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('line_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sides', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['production_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finishing_job_batch_id'), 'finishing_job', ['batch_id'], unique=False)
    op.create_index(op.f('ix_finishing_job_status'), 'finishing_job', ['status'], unique=False)
    op.create_table('log_processing',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('heating_vat_id', sa.Integer(), nullable=True),
    sa.Column('flitch_length_m', sa.Float(), nullable=True),
    sa.Column('flitch_diameter_m', sa.Float(), nullable=True),
    sa.Column('sawing_loss', sa.Float(), nullable=True),
    sa.Column('veneer_thickness_mm', sa.Float(), nullable=True),
    sa.Column('sliced_veneer_m2', sa.Float(), nullable=True),
    sa.Column('trimmed_veneer_m2', sa.Float(), nullable=True),
    sa.Column('final_yield_pct', sa.Float(), nullable=True),
    sa.Column('output_lot_id', sa.Integer(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['heating_vat_id'], ['heating_vat.id'], ),
    sa.ForeignKeyConstraint(['log_id'], ['log.id'], ),
    sa.ForeignKeyConstraint(['output_lot_id'], ['raw_material_lot.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['transformation_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_processing_log_id'), 'log_processing', ['log_id'], unique=False)
    op.create_index(op.f('ix_log_processing_run_id'), 'log_processing', ['run_id'], unique=False)
    op.create_table('splicing_record',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('input_lot_id', sa.Integer(), nullable=False),
    sa.Column('trim_loss', sa.Float(), nullable=True),
    sa.Column('sheet_count_4x8', sa.Integer(), nullable=True),
    sa.Column('output_lot_id', sa.Integer(), nullable=True),
    sa.Column('grade', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['input_lot_id'], ['raw_material_lot.id'], ),
    sa.ForeignKeyConstraint(['output_lot_id'], ['raw_material_lot.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['transformation_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_splicing_record_input_lot_id'), 'splicing_record', ['input_lot_id'], unique=False)
    op.create_index(op.f('ix_splicing_record_run_id'), 'splicing_record', ['run_id'], unique=False)
    op.drop_index(op.f('ix_transformation_step_run_id'), table_name='transformation_step')
    op.drop_table('transformation_step')
    op.drop_index(op.f('ix_transformation_output_run_id'), table_name='transformation_output')
    op.drop_table('transformation_output')
    op.drop_index(op.f('ix_transformation_input_run_id'), table_name='transformation_input')
    op.drop_table('transformation_input')
    op.add_column('production_batch', sa.Column('rework_pass', sa.Integer(), nullable=False))
    op.add_column('transformation_run', sa.Column('production_order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transformation_run', 'production_order', ['production_order_id'], ['id'])
    op.drop_column('transformation_run', 'mode')
    op.sync_enum_values(
        enum_schema='public',
        enum_name='bomlinerole',
        new_values=['BOARD', 'FACE_VENEER', 'BACK_VENEER', 'FACE_GLUE', 'BACK_GLUE', 'PACKING', 'PRIMER', 'COATING', 'UV_TOPCOAT', 'INPUT', 'OUTPUT', 'OTHER'],
        affected_columns=[TableReference(table_schema='public', table_name='bom_consumable', column_name='role'), TableReference(table_schema='public', table_name='bom_item', column_name='role')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='bomlinerole',
        new_values=['BOARD', 'FACE_VENEER', 'BACK_VENEER', 'FACE_GLUE', 'BACK_GLUE', 'PACKING', 'INPUT', 'OUTPUT', 'OTHER'],
        affected_columns=[TableReference(table_schema='public', table_name='bom_consumable', column_name='role'), TableReference(table_schema='public', table_name='bom_item', column_name='role')],
        enum_values_to_rename=[],
    )
    op.add_column('transformation_run', sa.Column('mode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transformation_run', type_='foreignkey')
    op.drop_column('transformation_run', 'production_order_id')
    op.drop_column('production_batch', 'rework_pass')
    op.create_table('transformation_input',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lot_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('uom', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['production_batch.id'], name=op.f('transformation_input_batch_id_fkey')),
    sa.ForeignKeyConstraint(['lot_id'], ['raw_material_lot.id'], name=op.f('transformation_input_lot_id_fkey')),
    sa.ForeignKeyConstraint(['run_id'], ['transformation_run.id'], name=op.f('transformation_input_run_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('transformation_input_pkey'))
    )
    op.create_index(op.f('ix_transformation_input_run_id'), 'transformation_input', ['run_id'], unique=False)
    op.create_table('transformation_output',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('grade', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('output_lot_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('uom', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('yield_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('fg_lot_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fg_lot_id'], ['fg_lot.id'], name=op.f('transformation_output_fg_lot_id_fkey')),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('transformation_output_item_id_fkey')),
    sa.ForeignKeyConstraint(['output_lot_id'], ['raw_material_lot.id'], name=op.f('transformation_output_output_lot_id_fkey')),
    sa.ForeignKeyConstraint(['run_id'], ['transformation_run.id'], name=op.f('transformation_output_run_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('transformation_output_pkey'))
    )
    op.create_index(op.f('ix_transformation_output_run_id'), 'transformation_output', ['run_id'], unique=False)
    op.create_table('transformation_step',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seq', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('input_qty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('input_uom', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('output_qty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('output_uom', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('loss_qty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['transformation_run.id'], name=op.f('transformation_step_run_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('transformation_step_pkey'))
    )
    op.create_index(op.f('ix_transformation_step_run_id'), 'transformation_step', ['run_id'], unique=False)
    op.drop_index(op.f('ix_splicing_record_run_id'), table_name='splicing_record')
    op.drop_index(op.f('ix_splicing_record_input_lot_id'), table_name='splicing_record')
    op.drop_table('splicing_record')
    op.drop_index(op.f('ix_log_processing_run_id'), table_name='log_processing')
    op.drop_index(op.f('ix_log_processing_log_id'), table_name='log_processing')
    op.drop_table('log_processing')
    op.drop_index(op.f('ix_finishing_job_status'), table_name='finishing_job')
    op.drop_index(op.f('ix_finishing_job_batch_id'), table_name='finishing_job')
    op.drop_table('finishing_job')
    op.drop_index(op.f('ix_log_document_log_id'), table_name='log_document')
    op.drop_table('log_document')
    op.drop_index(op.f('ix_transformation_recipe_line_recipe_id'), table_name='transformation_recipe_line')
    op.drop_index(op.f('ix_transformation_recipe_line_kind'), table_name='transformation_recipe_line')
    op.drop_table('transformation_recipe_line')
    op.drop_index(op.f('ix_log_log_number'), table_name='log')
    op.drop_index(op.f('ix_log_log_code'), table_name='log')
    op.drop_index(op.f('ix_log_arrival_id'), table_name='log')
    op.drop_table('log')
    op.drop_index(op.f('ix_log_arrival_arrival_code'), table_name='log_arrival')
    op.drop_table('log_arrival')
    op.drop_index(op.f('ix_transformation_recipe_line_code'), table_name='transformation_recipe')
    op.drop_index(op.f('ix_transformation_recipe_code'), table_name='transformation_recipe')
    op.drop_table('transformation_recipe')
    op.drop_index(op.f('ix_heating_vat_vat_number'), table_name='heating_vat')
    op.drop_table('heating_vat')
    # ### end Alembic commands ###
