"""barcode (10) + cost (11) - completes 12-domain schema

Revision ID: 40aebe2fed06
Revises: 9cac9e90aa3d
Create Date: 2026-07-06 15:09:52.637341
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40aebe2fed06'
down_revision: Union[str, None] = '9cac9e90aa3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barcode_label',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('symbology', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('printed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('printed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barcode_label_code'), 'barcode_label', ['code'], unique=True)
    op.create_index(op.f('ix_barcode_label_target_type'), 'barcode_label', ['target_type'], unique=False)
    op.create_table('scan_event',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('scanned_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('ref_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scanned_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['barcode_label.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['warehouse_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_event_label_id'), 'scan_event', ['label_id'], unique=False)
    op.create_table('batch_cost_record',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('material_cost', sa.Float(), nullable=False),
    sa.Column('conversion_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('cost_per_unit', sa.Float(), nullable=True),
    sa.Column('grade_allocation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['production_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_cost_record_batch_id'), 'batch_cost_record', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batch_cost_record_batch_id'), table_name='batch_cost_record')
    op.drop_table('batch_cost_record')
    op.drop_index(op.f('ix_scan_event_label_id'), table_name='scan_event')
    op.drop_table('scan_event')
    op.drop_index(op.f('ix_barcode_label_target_type'), table_name='barcode_label')
    op.drop_index(op.f('ix_barcode_label_code'), table_name='barcode_label')
    op.drop_table('barcode_label')
    # ### end Alembic commands ###
