"""fg lots + traceability spine + transformation fg link

Revision ID: 476255ba1215
Revises: 05b98cf23661
Create Date: 2026-07-06 14:19:35.535318
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '476255ba1215'
down_revision: Union[str, None] = '05b98cf23661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fg_lot',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('production_batch_id', sa.Integer(), nullable=True),
    sa.Column('grade', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('uom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('produced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['warehouse_location.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['production_batch_id'], ['production_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fg_lot_lot_code'), 'fg_lot', ['lot_code'], unique=True)
    op.create_index(op.f('ix_fg_lot_product_id'), 'fg_lot', ['product_id'], unique=False)
    op.create_table('dispatch_line',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('fg_lot_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('uom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['fg_lot_id'], ['fg_lot.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_line_fg_lot_id'), 'dispatch_line', ['fg_lot_id'], unique=False)
    op.create_index(op.f('ix_dispatch_line_shipment_id'), 'dispatch_line', ['shipment_id'], unique=False)
    op.create_table('lot_linkage',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_lot_id', sa.Integer(), nullable=True),
    sa.Column('parent_batch_id', sa.Integer(), nullable=True),
    sa.Column('parent_fg_lot_id', sa.Integer(), nullable=True),
    sa.Column('child_lot_id', sa.Integer(), nullable=True),
    sa.Column('child_batch_id', sa.Integer(), nullable=True),
    sa.Column('child_fg_lot_id', sa.Integer(), nullable=True),
    sa.Column('relation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('uom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ref_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['child_batch_id'], ['production_batch.id'], ),
    sa.ForeignKeyConstraint(['child_fg_lot_id'], ['fg_lot.id'], ),
    sa.ForeignKeyConstraint(['child_lot_id'], ['raw_material_lot.id'], ),
    sa.ForeignKeyConstraint(['parent_batch_id'], ['production_batch.id'], ),
    sa.ForeignKeyConstraint(['parent_fg_lot_id'], ['fg_lot.id'], ),
    sa.ForeignKeyConstraint(['parent_lot_id'], ['raw_material_lot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lot_linkage_child_lot_id'), 'lot_linkage', ['child_lot_id'], unique=False)
    op.create_index(op.f('ix_lot_linkage_parent_lot_id'), 'lot_linkage', ['parent_lot_id'], unique=False)
    op.add_column('transformation_output', sa.Column('fg_lot_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transformation_output', 'fg_lot', ['fg_lot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transformation_output', type_='foreignkey')
    op.drop_column('transformation_output', 'fg_lot_id')
    op.drop_index(op.f('ix_lot_linkage_parent_lot_id'), table_name='lot_linkage')
    op.drop_index(op.f('ix_lot_linkage_child_lot_id'), table_name='lot_linkage')
    op.drop_table('lot_linkage')
    op.drop_index(op.f('ix_dispatch_line_shipment_id'), table_name='dispatch_line')
    op.drop_index(op.f('ix_dispatch_line_fg_lot_id'), table_name='dispatch_line')
    op.drop_table('dispatch_line')
    op.drop_index(op.f('ix_fg_lot_product_id'), table_name='fg_lot')
    op.drop_index(op.f('ix_fg_lot_lot_code'), table_name='fg_lot')
    op.drop_table('fg_lot')
    # ### end Alembic commands ###
