"""master data: item, product, category, species, location, supplier

Revision ID: 8065048a6cb7
Revises: 82a8d875416d
Create Date: 2026-07-03 14:01:29.751835
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8065048a6cb7'
down_revision: Union[str, None] = '82a8d875416d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_category',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_category_code'), 'product_category', ['code'], unique=True)
    op.create_table('species',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('common_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('botanical_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_species_code'), 'species', ['code'], unique=True)
    op.create_table('supplier',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_person', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_code'), 'supplier', ['code'], unique=True)
    op.create_table('warehouse_location',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_location_code'), 'warehouse_location', ['code'], unique=True)
    op.create_table('item',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('kind', sa.Enum('VENEER', 'BOARD', 'GLUE_COMPONENT', 'CONSUMABLE', 'PACKING', 'OTHER', name='itemkind'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_th', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_zh', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=True),
    sa.Column('grade', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cut_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('matching', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('face_back', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fsc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('board_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('glue_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auto_glue_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thickness_mm', sa.Float(), nullable=True),
    sa.Column('width_mm', sa.Float(), nullable=True),
    sa.Column('length_mm', sa.Float(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('fc_unit_cost', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('acc_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reorder_point', sa.Float(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_code'), 'item', ['code'], unique=True)
    op.create_index(op.f('ix_item_kind'), 'item', ['kind'], unique=False)
    op.create_table('product',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('thickness_mm', sa.Float(), nullable=True),
    sa.Column('width_mm', sa.Float(), nullable=True),
    sa.Column('length_mm', sa.Float(), nullable=True),
    sa.Column('pallet_qty', sa.Integer(), nullable=False),
    sa.Column('approved_date', sa.Date(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_code'), 'product', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_code'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_item_kind'), table_name='item')
    op.drop_index(op.f('ix_item_code'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_warehouse_location_code'), table_name='warehouse_location')
    op.drop_table('warehouse_location')
    op.drop_index(op.f('ix_supplier_code'), table_name='supplier')
    op.drop_table('supplier')
    op.drop_index(op.f('ix_species_code'), table_name='species')
    op.drop_table('species')
    op.drop_index(op.f('ix_product_category_code'), table_name='product_category')
    op.drop_table('product_category')
    # ### end Alembic commands ###
