"""procurement (PO/POLine/GoodsReceipt) + fc grading

Revision ID: 9cac9e90aa3d
Revises: 476255ba1215
Create Date: 2026-07-06 15:05:15.951852
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cac9e90aa3d'
down_revision: Union[str, None] = '476255ba1215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_order',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PENDING', 'PLANNED', 'OPEN', 'IN_PROGRESS', 'PARTIAL', 'RELEASED', 'COMPLETED', 'CANCELLED', name='orderstatus', create_type=False), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_po_number'), 'purchase_order', ['po_number'], unique=True)
    op.create_index(op.f('ix_purchase_order_supplier_id'), 'purchase_order', ['supplier_id'], unique=False)
    op.create_table('po_line',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('qty_ordered', sa.Float(), nullable=False),
    sa.Column('qty_received', sa.Float(), nullable=False),
    sa.Column('uom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_po_line_purchase_order_id'), 'po_line', ['purchase_order_id'], unique=False)
    op.create_table('goods_receipt',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('po_line_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('qty_received', sa.Float(), nullable=False),
    sa.Column('uom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['warehouse_location.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['raw_material_lot.id'], ),
    sa.ForeignKeyConstraint(['po_line_id'], ['po_line.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_receipt_receipt_number'), 'goods_receipt', ['receipt_number'], unique=True)
    op.create_table('fc_grading_record',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('grader', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_qty', sa.Float(), nullable=False),
    sa.Column('uom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grade_split', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ncg_qty', sa.Float(), nullable=False),
    sa.Column('reject_qty', sa.Float(), nullable=False),
    sa.Column('cost_allocation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['production_batch.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['raw_material_lot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fc_grading_record_batch_id'), 'fc_grading_record', ['batch_id'], unique=False)
    op.create_index(op.f('ix_fc_grading_record_lot_id'), 'fc_grading_record', ['lot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fc_grading_record_lot_id'), table_name='fc_grading_record')
    op.drop_index(op.f('ix_fc_grading_record_batch_id'), table_name='fc_grading_record')
    op.drop_table('fc_grading_record')
    op.drop_index(op.f('ix_goods_receipt_receipt_number'), table_name='goods_receipt')
    op.drop_table('goods_receipt')
    op.drop_index(op.f('ix_po_line_purchase_order_id'), table_name='po_line')
    op.drop_table('po_line')
    op.drop_index(op.f('ix_purchase_order_supplier_id'), table_name='purchase_order')
    op.drop_index(op.f('ix_purchase_order_po_number'), table_name='purchase_order')
    op.drop_table('purchase_order')
    # ### end Alembic commands ###
