"""rm lot domain: raw_material_lot + lot_movement

Revision ID: bc154533a423
Revises: ed07f307bc25
Create Date: 2026-07-06 13:33:40.975681
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bc154533a423'
down_revision: Union[str, None] = 'ed07f307bc25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_material_lot',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.Enum('RECEIVED', 'TRANSFORMED', 'ADJUSTED', 'OPENING', name='lotorigin'), nullable=False),
    sa.Column('grade', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('supplier_lot_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('received_qty', sa.Float(), nullable=False),
    sa.Column('remaining_qty', sa.Float(), nullable=False),
    sa.Column('uom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['warehouse_location.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_material_lot_item_id'), 'raw_material_lot', ['item_id'], unique=False)
    op.create_index(op.f('ix_raw_material_lot_lot_code'), 'raw_material_lot', ['lot_code'], unique=True)
    op.create_table('lot_movement',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Enum('RECEIVE', 'TRANSFER', 'ADJUST', 'CONSUME', 'PRODUCE', 'GRADE', 'SPLICE', 'CUT_RESIZE', 'SHIP', 'SCRAP', name='movementtype'), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('uom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_location_id', sa.Integer(), nullable=True),
    sa.Column('to_location_id', sa.Integer(), nullable=True),
    sa.Column('ref_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('moved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('moved_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['from_location_id'], ['warehouse_location.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['raw_material_lot.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['warehouse_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lot_movement_lot_id'), 'lot_movement', ['lot_id'], unique=False)
    op.create_index(op.f('ix_lot_movement_movement_type'), 'lot_movement', ['movement_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lot_movement_movement_type'), table_name='lot_movement')
    op.drop_index(op.f('ix_lot_movement_lot_id'), table_name='lot_movement')
    op.drop_table('lot_movement')
    op.drop_index(op.f('ix_raw_material_lot_lot_code'), table_name='raw_material_lot')
    op.drop_index(op.f('ix_raw_material_lot_item_id'), table_name='raw_material_lot')
    op.drop_table('raw_material_lot')
    # ### end Alembic commands ###
