"""catalog: manufacturing_line, department, line_flow, station

Revision ID: debe45413562
Revises: 40aebe2fed06
Create Date: 2026-07-07 13:39:10.925729
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'debe45413562'
down_revision: Union[str, None] = '40aebe2fed06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_centralised', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('manufacturing_line',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('line_id', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('line_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('line_id')
    )
    op.create_table('line_flow',
    sa.Column('line_code', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('department_code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.ForeignKeyConstraint(['department_code'], ['department.code'], ),
    sa.ForeignKeyConstraint(['line_code'], ['manufacturing_line.line_id'], ),
    sa.PrimaryKeyConstraint('line_code', 'seq')
    )
    op.create_table('station',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_code', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('department_code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('capacity_per_shift', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_code'], ['department.code'], ),
    sa.ForeignKeyConstraint(['line_code'], ['manufacturing_line.line_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_code', 'department_code', name='uq_station_line_dept')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('station')
    op.drop_table('line_flow')
    op.drop_table('manufacturing_line')
    op.drop_table('department')
    # ### end Alembic commands ###
