"""bom domain: glue_recipe, bom_group/header/item/consumable

Revision ID: ed07f307bc25
Revises: ae3f35f988b0
Create Date: 2026-07-06 13:13:05.394416
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed07f307bc25'
down_revision: Union[str, None] = 'ae3f35f988b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bom_group',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('calc_method', sa.Enum('PER_SHEET', 'PER_PALLET', name='calcmethod'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('glue_recipe',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resin_ratio', sa.Float(), nullable=False),
    sa.Column('hardener_ratio', sa.Float(), nullable=False),
    sa.Column('extender_ratio', sa.Float(), nullable=False),
    sa.Column('filler_ratio', sa.Float(), nullable=False),
    sa.Column('water_ratio', sa.Float(), nullable=False),
    sa.Column('mix_time_min', sa.Integer(), nullable=False),
    sa.Column('material_links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glue_recipe_recipe_code'), 'glue_recipe', ['recipe_code'], unique=True)
    op.create_table('bom_header',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('bom_type', sa.Enum('ASSEMBLY', 'TRANSFORMATION', name='bomtype'), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'revision', name='uq_bom_product_rev')
    )
    op.create_index(op.f('ix_bom_header_product_id'), 'bom_header', ['product_id'], unique=False)
    op.create_table('bom_consumable',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bom_header_id', sa.Integer(), nullable=False),
    sa.Column('glue_recipe_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('BOARD', 'FACE_VENEER', 'BACK_VENEER', 'FACE_GLUE', 'BACK_GLUE', 'PACKING', 'INPUT', 'OUTPUT', 'OTHER', name='bomlinerole'), nullable=False),
    sa.Column('usage_g_per_face', sa.Float(), nullable=True),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('qty_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.CheckConstraint('glue_recipe_id IS NOT NULL OR item_id IS NOT NULL', name='ck_bomconsumable_target'),
    sa.ForeignKeyConstraint(['bom_header_id'], ['bom_header.id'], ),
    sa.ForeignKeyConstraint(['glue_recipe_id'], ['glue_recipe.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bom_consumable_bom_header_id'), 'bom_consumable', ['bom_header_id'], unique=False)
    op.create_table('bom_item',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bom_header_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('BOARD', 'FACE_VENEER', 'BACK_VENEER', 'FACE_GLUE', 'BACK_GLUE', 'PACKING', 'INPUT', 'OUTPUT', 'OTHER', name='bomlinerole'), nullable=False),
    sa.Column('qty_override', sa.Float(), nullable=True),
    sa.Column('qty_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('waste_factor', sa.Float(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['bom_header_id'], ['bom_header.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['bom_group.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bom_header_id', 'seq', name='uq_bomitem_header_seq')
    )
    op.create_index(op.f('ix_bom_item_bom_header_id'), 'bom_item', ['bom_header_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bom_item_bom_header_id'), table_name='bom_item')
    op.drop_table('bom_item')
    op.drop_index(op.f('ix_bom_consumable_bom_header_id'), table_name='bom_consumable')
    op.drop_table('bom_consumable')
    op.drop_index(op.f('ix_bom_header_product_id'), table_name='bom_header')
    op.drop_table('bom_header')
    op.drop_index(op.f('ix_glue_recipe_recipe_code'), table_name='glue_recipe')
    op.drop_table('glue_recipe')
    op.drop_table('bom_group')
    # ### end Alembic commands ###
