"""unify aux lines into batch model: drop transform-run tables, dept strings, batch_movement

Revision ID: faafa3e04a81
Revises: 2edddf20dcb4
Create Date: 2026-07-16 14:42:30.926960
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'faafa3e04a81'
down_revision: Union[str, None] = '2edddf20dcb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_movement',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('from_department', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('to_department', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('time_in_dept_min', sa.Integer(), nullable=False),
    sa.Column('moved_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('moved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['production_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_movement_batch_id'), 'batch_movement', ['batch_id'], unique=False)
    op.drop_index(op.f('ix_finishing_job_batch_id'), table_name='finishing_job')
    op.drop_index(op.f('ix_finishing_job_status'), table_name='finishing_job')
    op.drop_table('finishing_job')
    op.drop_index(op.f('ix_log_processing_log_id'), table_name='log_processing')
    op.drop_index(op.f('ix_log_processing_run_id'), table_name='log_processing')
    op.drop_table('log_processing')
    op.drop_index(op.f('ix_splicing_record_input_lot_id'), table_name='splicing_record')
    op.drop_index(op.f('ix_splicing_record_run_id'), table_name='splicing_record')
    op.drop_table('splicing_record')
    op.drop_index(op.f('ix_transformation_run_line_code'), table_name='transformation_run')
    op.drop_index(op.f('ix_transformation_run_run_number'), table_name='transformation_run')
    op.drop_table('transformation_run')
    op.add_column('production_batch', sa.Column('current_department', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index(op.f('ix_production_batch_current_station'), table_name='production_batch')
    op.create_index(op.f('ix_production_batch_current_department'), 'production_batch', ['current_department'], unique=False)
    op.drop_column('production_batch', 'current_station')
    op.add_column('station_record', sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index(op.f('ix_station_record_station'), table_name='station_record')
    op.create_index(op.f('ix_station_record_department'), 'station_record', ['department'], unique=False)
    op.drop_column('station_record', 'station')
    sa.Enum('FC', 'LAMINATING', 'COLD_PRESS', 'HOT_PRESS', 'BLEACH', 'REPAIR', 'SANDING', 'GRADING', 'PACKING', 'FG_RECEIVING', 'FG_WAREHOUSE', name='stationcode').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('FC', 'LAMINATING', 'COLD_PRESS', 'HOT_PRESS', 'BLEACH', 'REPAIR', 'SANDING', 'GRADING', 'PACKING', 'FG_RECEIVING', 'FG_WAREHOUSE', name='stationcode').create(op.get_bind())
    op.add_column('station_record', sa.Column('station', postgresql.ENUM('FC', 'LAMINATING', 'COLD_PRESS', 'HOT_PRESS', 'BLEACH', 'REPAIR', 'SANDING', 'GRADING', 'PACKING', 'FG_RECEIVING', 'FG_WAREHOUSE', name='stationcode', create_type=False), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_station_record_department'), table_name='station_record')
    op.create_index(op.f('ix_station_record_station'), 'station_record', ['station'], unique=False)
    op.drop_column('station_record', 'department')
    op.add_column('production_batch', sa.Column('current_station', postgresql.ENUM('FC', 'LAMINATING', 'COLD_PRESS', 'HOT_PRESS', 'BLEACH', 'REPAIR', 'SANDING', 'GRADING', 'PACKING', 'FG_RECEIVING', 'FG_WAREHOUSE', name='stationcode', create_type=False), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_production_batch_current_department'), table_name='production_batch')
    op.create_index(op.f('ix_production_batch_current_station'), 'production_batch', ['current_station'], unique=False)
    op.drop_column('production_batch', 'current_department')
    op.create_table('splicing_record',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('input_lot_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trim_loss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sheet_count_4x8', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('output_lot_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grade', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['input_lot_id'], ['raw_material_lot.id'], name=op.f('splicing_record_input_lot_id_fkey')),
    sa.ForeignKeyConstraint(['output_lot_id'], ['raw_material_lot.id'], name=op.f('splicing_record_output_lot_id_fkey')),
    sa.ForeignKeyConstraint(['run_id'], ['transformation_run.id'], name=op.f('splicing_record_run_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('splicing_record_pkey'))
    )
    op.create_index(op.f('ix_splicing_record_run_id'), 'splicing_record', ['run_id'], unique=False)
    op.create_index(op.f('ix_splicing_record_input_lot_id'), 'splicing_record', ['input_lot_id'], unique=False)
    op.create_table('log_processing',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('log_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('heating_vat_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('flitch_length_m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('flitch_diameter_m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sawing_loss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('veneer_thickness_mm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sliced_veneer_m2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('trimmed_veneer_m2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('final_yield_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('output_lot_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['heating_vat_id'], ['heating_vat.id'], name=op.f('log_processing_heating_vat_id_fkey')),
    sa.ForeignKeyConstraint(['log_id'], ['log.id'], name=op.f('log_processing_log_id_fkey')),
    sa.ForeignKeyConstraint(['output_lot_id'], ['raw_material_lot.id'], name=op.f('log_processing_output_lot_id_fkey')),
    sa.ForeignKeyConstraint(['run_id'], ['transformation_run.id'], name=op.f('log_processing_run_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('log_processing_pkey'))
    )
    op.create_index(op.f('ix_log_processing_run_id'), 'log_processing', ['run_id'], unique=False)
    op.create_index(op.f('ix_log_processing_log_id'), 'log_processing', ['log_id'], unique=False)
    op.create_table('transformation_run',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('run_number', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('line_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('operator_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('operator_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('machine', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PENDING', 'PLANNED', 'OPEN', 'IN_PROGRESS', 'PARTIAL', 'RELEASED', 'COMPLETED', 'CANCELLED', name='orderstatus', create_type=False), autoincrement=False, nullable=False),
    sa.Column('run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('production_order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_order.id'], name=op.f('transformation_run_production_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('transformation_run_pkey'))
    )
    op.create_index(op.f('ix_transformation_run_run_number'), 'transformation_run', ['run_number'], unique=True)
    op.create_index(op.f('ix_transformation_run_line_code'), 'transformation_run', ['line_code'], unique=False)
    op.create_table('finishing_job',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('line_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sides', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('requested_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['production_batch.id'], name=op.f('finishing_job_batch_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('finishing_job_pkey'))
    )
    op.create_index(op.f('ix_finishing_job_status'), 'finishing_job', ['status'], unique=False)
    op.create_index(op.f('ix_finishing_job_batch_id'), 'finishing_job', ['batch_id'], unique=False)
    op.drop_index(op.f('ix_batch_movement_batch_id'), table_name='batch_movement')
    op.drop_table('batch_movement')
    # ### end Alembic commands ###
